### PR TITLE
annotate dev packages with --editable

### PR DESCRIPTION
**Pull request by matthiasdiener**
Complements https://github.com/illinois-ceesd/emirge/pull/113

### CODE REVIEW

**Comment by inducer** [comment]
I don't know that this is a good idea, as it impacts the reusability of mirgecom. What if these packages are already installed? AFAICT, if I were to use this in a virtualenv that already has all those packages, those would get uninstalled and replaced by fresh checkouts under mirgecom.

**Comment by matthiasdiener** [comment]
> I don't know that this is a good idea, as it impacts the reusability of mirgecom. What if these packages are already installed? AFAICT, if I were to use this in a virtualenv that already has all those packages, those would get uninstalled and replaced by fresh checkouts under mirgecom.

Hmm, wouldn't that be the intention, to install the exact versions that mirgecom requires?

**Comment by inducer** [comment]
> Edit: Do you mean this in the context of when someone is installing mirgecom without emirge?

Yes. (That's me, most of the time.)

**Comment by inducer** [comment]
(OTOH, IMO this is minor. I won't oppose it.)

**Comment by MTCam** [comment]
Insomuch as this is designed to support hand-off of installation responsibility of development packages from `emirge` -> `pip` (via https://github.com/illinois-ceesd/emirge/pull/113), I'm all for it.  

I am a little more unsure about the potential subtle issues or unintended consequences that might impact others' use of `emirge` as a result of these changes, including those in https://github.com/illinois-ceesd/emirge/pull/113.

But just the fact that we need to be soo cautious about changing this simple behavior of `emirge` and the potential fallout; to me is an indicator that `emirge` is too complex for a `MIRGE-Com` installation tool, and anything we can do to reduce its complexity would be a good move.  Exporting `requirements.txt` parsing to `pip` is a kind of low-hanging fruit pursuant to that goal.

**Comment by matthiasdiener** [comment]
> I don't know that this is a good idea, as it impacts the reusability of mirgecom. What if these packages are already installed? AFAICT, if I were to use this in a virtualenv that already has all those packages, those would get uninstalled and replaced by fresh checkouts under mirgecom.

I've done a few tests, and afaics the behavior with and without `--editable` is the same: it uninstalls a previously installed package (whether that was installed through git or not), and installs the new version.

**Review by MTCam — APPROVED** [review]

**Comment by inducer** [comment]
I can always delete the `--editable`, so I won't oppose this.

**Pull request merged**
