### PR TITLE
ci: test emirge install

### PR DESCRIPTION
**Pull request by matthiasdiener**
We could change the "normal" CI tests to use emirge too, but I would like to observe how this behaves for a week or so before doing that change.

### CODE REVIEW

**Review by MTCam — COMMENTED** [review]
This is a good idea I think.  

If we did make `emirge` the installation method for the tests, then I guess we'd need `--branch-name=` to work properly.  Is there any value to adding a branch-specific install test or so to round it out?

**Comment by matthiasdiener** [comment]
> This is a good idea I think.
> 
> If we did make `emirge` the installation method for the tests, then I guess we'd need `--branch-name=` to work properly. Is there any value to adding a branch-specific install test or so to round it out?

`--branch` won't work currently with forks, which is why this CI test is copying over the checked-out mirgecom files into the emirge folder to use the mirgecom version that is under review. This should work with PRs from branches in this repo as well as forked repos. Unfortunately, there seems to be no easy way to do this without the copying step.

**Comment by MTCam** [comment]
> `--branch` won't work currently with forks, which is why this CI test is copying over the checked-out mirgecom files into the emirge folder to install the mirgecom version that is under review. This should work with PRs from branches in this repo as well as forked repos. Unfortunately, there seems to be no easy way to do this without the copying step.

oic. the copy seems like a good fix for that issue. tested?

**Comment by matthiasdiener** [comment]
> > `--branch` won't work currently with forks, which is why this CI test is copying over the checked-out mirgecom files into the emirge folder to install the mirgecom version that is under review. This should work with PRs from branches in this repo as well as forked repos. Unfortunately, there seems to be no easy way to do this without the copying step.
> 
> oic. the copy seems like a good fix for that issue. tested?

test works with https://github.com/illinois-ceesd/emirge/pull/110

**Review by MTCam — COMMENTED** [review]
I'm not afraid if you're not 👍

**Review by MTCam — APPROVED** [review]
Looks good to me :)

**Pull request merged**
