### PR TITLE
Add cross-rank flux to wave operator

### PR DESCRIPTION
**Pull request by majosm**

### CODE REVIEW

**Comment by inducer** [comment]
Is there a test for MPI wave?

**Comment by inducer** [comment]
@majosm Just looked over our pending PRs and saw this hanging out. I won't insist on an MPI+wave test. It's still better to have this than not, as long as wave-eager works with MPI.

**Comment by inducer** [comment]
(But it looks like it has picked up some conflicts. Could you take a look?)

**Comment by majosm** [comment]
Yeah, I think this is what originally got me started on the MPI testing stuff I've been working on. I was planning to come back and parallelize the wave tests afterwards, but I can do that later.

I updated the branch and re-ran `wave-eager-mpi` -- everything still looks good.

**Review by inducer — APPROVED** [review]

**Pull request merged**
