### PR TITLE
Run examples on porter

### PR DESCRIPTION
**Pull request by matthiasdiener**
https://github.com/illinois-ceesd/planning/wiki/Porter-CI

**Questions for the review**:
- [ ] Is the scope and purpose of the PR clear?
  - [ ] The PR should have a description.
  - [ ] The PR should have a guide if needed (e.g., an ordering).
- [ ] Is every top-level method and class documented? Are things that should be documented actually so?
- [ ] Is the interface understandable? (I.e. can someone figure out what stuff does?) Is it well-defined?
- [ ] Does the implementation do what the docstring claims?
- [ ] Is everything that is implemented covered by tests?
- [ ] Do you see any immediate risks or performance disadvantages with the design? Example: what do interface normals attach to?

### CODE REVIEW

**Comment by inducer** [comment]
Generally that looks good, but we'll need to fix the example failure.

**Comment by matthiasdiener** [comment]
> Generally that looks good, but we'll need to fix the example failure.

[775525c](https://github.com/illinois-ceesd/mirgecom/pull/653/commits/775525ce1db1ad110d79f49e1151e50ba84cd8b5) works around it.

**Comment by matthiasdiener** [comment]
This is ready for review

**Review by inducer — APPROVED** [review]
Thx!

**Pull request merged**
