### PR TITLE
Add heat equation solver

### PR DESCRIPTION
**Pull request by majosm**

### CODE REVIEW

**Comment by majosm** [comment]
@inducer, @lukeolson Any ideas what might cause order N-1 convergence?

CI jobs aren't running at the moment, but I'm seeing results like the following:

N == 2:
-------
```
test_heat.py::test_heat_accuracy[<array context factory for <pyopencl.Device 'pthread' on 'Portable Computing Language'>-2-problem0] Approximation error:
h         | Error               | Running EOC       
----------+---------------------+--------------------
0.25      | 1.7834496275775333  |                   
0.125     | 0.6968572287595005  | 1.3557354544393743
0.0625    | 0.31670333794087324 | 1.1377310358661137
0.03125   | 0.15230421159162905 | 1.0561762364444538
0.015625  | 0.07483467000993342 | 1.0251771229925633
0.0078125 | 0.03710968141446858 | 1.0119111927969053

Overall EOC: 1.1042024181443106
```

N == 3:
-------
```
test_heat.py::test_heat_accuracy[<array context factory for <pyopencl.Device 'pthread' on 'Portable Computing Language'>-3-problem0] Approximation error:
h         | Error                 | Running EOC       
----------+-----------------------+--------------------
0.25      | 0.6610622776093845    |                   
0.125     | 0.16020897329634504   | 2.0448312368203445
0.0625    | 0.038383352453954044  | 2.0614023261980385
0.03125   | 0.009168145283721212  | 2.0657789128071284
0.015625  | 0.0022301145386689797 | 2.039512097197309 
0.0078125 | 0.0005493927867850215 | 2.0212079349718763

Overall EOC: 2.049414898896799
```

N == 4:
-------
```
test_heat.py::test_heat_accuracy[<array context factory for <pyopencl.Device 'pthread' on 'Portable Computing Language'>-4-problem0] Approximation error:
h         | Error                  | Running EOC       
----------+------------------------+--------------------
0.25      | 0.16282218246328947    |                   
0.125     | 0.012285691904369312   | 3.7282462472929456
0.0625    | 0.0012310465783365676  | 3.319021855228969 
0.03125   | 0.00013900081879875356 | 3.1467200627702905
0.015625  | 1.654770402600909e-05  | 3.0703904174862995
0.0078125 | 2.0194376196686667e-06 | 3.034605571658565 

Overall EOC: 3.2357153668974923
```

Plotted error looks like this (u == decaying 2D cosine bump, N == 3, 8x8 grid):

error

**Comment by inducer** [comment]
Thanks for getting this working (at least in a preliminary way) and reporting convergence data. What are you taking the norm of? `u`? Or `[u, grad u]`? Have you looked through the literature/the book to see what is known? It looks like the error is dominated by jumps.

**Comment by majosm** [comment]
The data above is just for `u`, but I get similar results for `[u, q]`. The results I've found in the book and literature show order N convergence for even N, and N-1 for odd. These are for 1D though (not sure if it can be different for higher dimensions?)

**Comment by majosm** [comment]
With the new Nodal-DG interop functionality in meshmode I was able to modify my test to call the book's 1D heat operator in place of mirgecom's (code [here](https://github.com/majosm/mirgecom/blob/aa5e4b1f68cf0b80568190894f356d446e0bbcf6/test/test_heat.py#L152-L202)). Annnndddd... I get the same results (just about) for the convergence rate:

| Order | mirgecom | nodal-dg |
|-------|-----------|-----------|
| 1 | 1.041839116676463 | 1.0418391166740932 |
| 2 | 1.0954451731838413 | 1.095445173125385 |
| 3 | 3.1915488491254687 | 3.1915657378418554 |
| 4 | 3.2192263224503224 | 3.2192277161528495 |

What could this mean?

**Comment by inducer** [comment]
If you run the book code (maybe via octave, which is installed on the beers), can you reproduce the convergence results they present?

**Comment by majosm** [comment]
Seems like I get the same results as mirgecom. With [this script](https://github.com/majosm/mirgecom/blob/a0c8c5105b80b1248c226c1c82757c940e798d3b/test/HeatConvergence.m), I see the following output (left column is error, right column is order estimate):

N == 1:
-------
```
      0.1953792912171132
      0.1099221740958028       0.8297951163395746
      0.0565814366190629       0.9580817311390243
      0.0284962135261049       0.9895585757361663
      0.0142738866903134       0.9973920067401324
      0.0071401687490980       0.9993481490767304
```

N == 2:
-------
```
      0.1215177777189031
      0.0581808960155194       1.0625499716520841
      0.0287010480051059       1.0194420976644651
      0.0142996459074321       1.0051239942318924
      0.0071433935062815       1.0012979209516739
      0.0035708908896904       1.0003255445411368
```

N == 3:
-------
```
      0.0090388674277350
      0.0012064490669895       2.9053750037648762
      0.0001533261321326       2.9760915014320548
      0.0000192455386566       2.9940076477096786
      0.0000024082022271       2.9984955991980446
      0.0000003011336296       2.9994808089536447
```

N == 4:
-------
```
      0.0016791018271997
      0.0002100688172022       2.9987557953985942
      0.0000262324147009       3.0014395036989674
      0.0000032779727588       3.0004748439501587
      0.0000004097158306       3.0001083234199237
      0.0000000512525754       2.9989272298448588
```

**Comment by inducer** [comment]
cc @lukeolson

**Comment by inducer** [comment]
To put this in direct contrast, the book shows different results:

image

Specifically:
- for N even, they claim EOC N+1, while we observe (and our use of their code yields) N-1.
- for N odd, they claim EOC N, which we (and our use of their code) match.

So. Odd.

**Comment by majosm** [comment]
Out of curiosity, I tried computing the errors and convergence rates for each unit node individually:

N == 1:
-------
```
1.95e-01 1.95e-01 
1.10e-01 1.10e-01 ,  0.8298   0.8298 
5.66e-02 5.66e-02 ,  0.9581   0.9581 
2.85e-02 2.85e-02 ,  0.9896   0.9896 
1.43e-02 1.43e-02 ,  0.9974   0.9974 
7.14e-03 7.14e-03 ,  0.9993   0.9993 
```

N == 2:
-------
```
1.22e-01 1.74e-02 1.22e-01 
5.82e-02 4.94e-03 5.82e-02 ,  1.0625   1.8204   1.0625 
2.87e-02 1.27e-03 2.87e-02 ,  1.0194   1.9559   1.0194 
1.43e-02 3.21e-04 1.43e-02 ,  1.0051   1.9890   1.0051 
7.14e-03 8.03e-05 7.14e-03 ,  1.0013   1.9973   1.0013 
3.57e-03 2.01e-05 3.57e-03 ,  1.0003   1.9993   1.0003 
```

N == 3:
-------
```
9.04e-03 1.60e-03 1.60e-03 9.04e-03 
1.21e-03 2.27e-04 2.27e-04 1.21e-03 ,  2.9054   2.8158   2.8158   2.9054 
1.53e-04 2.92e-05 2.92e-05 1.53e-04 ,  2.9761   2.9547   2.9547   2.9761 
1.92e-05 3.68e-06 3.68e-06 1.92e-05 ,  2.9940   2.9887   2.9887   2.9940 
2.41e-06 4.61e-07 4.61e-07 2.41e-06 ,  2.9985   2.9972   2.9972   2.9985 
3.01e-07 5.77e-08 5.77e-08 3.01e-07 ,  2.9996   2.9991   2.9991   2.9995 
```

N == 4:
-------
```
1.68e-03 1.07e-04 9.33e-05 1.07e-04 1.68e-03 
2.10e-04 7.61e-06 6.66e-06 7.61e-06 2.10e-04 ,  2.9988   3.8116   3.8092   3.8116   2.9988 
2.62e-05 4.91e-07 4.30e-07 4.91e-07 2.62e-05 ,  3.0014   3.9538   3.9532   3.9538   3.0014 
3.28e-06 3.09e-08 2.71e-08 3.09e-08 3.28e-06 ,  3.0005   3.9885   3.9884   3.9885   3.0005 
4.10e-07 1.94e-09 1.70e-09 1.94e-09 4.10e-07 ,  3.0001   3.9971   3.9966   3.9955   3.0002 
5.13e-08 1.25e-10 1.11e-10 1.33e-10 5.12e-08 ,  2.9989   3.9542   3.9369   3.8657   3.0001 
```

Looks like we gain an order on the element interiors when N is even (still only order N though, not the expected N+1). Not sure if this tells us anything useful, but I figured I'd drop it here just in case.

**Comment by majosm** [comment]
You were right @inducer, time integrating and looking at `u` instead of `rhs` does have an effect. I can reproduce the book's results now with their code:

N == 1:
-------
```
6.18e-02 6.18e-02 
3.26e-02 3.26e-02 ,  0.9247   0.9247 
1.65e-02 1.65e-02 ,  0.9835   0.9835 
8.26e-03 8.26e-03 ,  0.9960   0.9960 
4.13e-03 4.13e-03 ,  0.9990   0.9990 
2.07e-03 2.07e-03 ,  0.9998   0.9998 
```

N == 2:
-------
```
3.46e-03 1.80e-04 3.46e-03 
4.02e-04 1.01e-05 4.02e-04 ,  3.1057   4.1648   3.1057 
4.94e-05 6.09e-07 4.94e-05 ,  3.0254   4.0448   3.0254 
6.15e-06 3.78e-08 6.15e-06 ,  3.0063   4.0114   3.0063 
7.68e-07 2.36e-09 7.68e-07 ,  3.0016   4.0029   3.0016 
9.60e-08 1.47e-10 9.60e-08 ,  3.0004   4.0007   3.0004 
```

N == 3:
-------
```
4.01e-04 1.71e-04 1.71e-04 4.01e-04 
4.94e-05 2.18e-05 2.18e-05 4.94e-05 ,  3.0221   2.9674   2.9674   3.0221 
6.15e-06 2.74e-06 2.74e-06 6.15e-06 ,  3.0056   2.9924   2.9924   3.0056 
7.68e-07 3.43e-07 3.43e-07 7.68e-07 ,  3.0014   2.9981   2.9981   3.0014 
9.60e-08 4.29e-08 4.29e-08 9.60e-08 ,  3.0003   2.9995   2.9995   3.0003 
1.20e-08 5.36e-09 5.36e-09 1.20e-08 ,  3.0001   2.9999   2.9999   3.0001 
```

N == 4:
-------
```
8.41e-06 2.50e-06 9.45e-07 2.50e-06 8.41e-06 
2.46e-07 7.00e-08 1.48e-08 7.00e-08 2.46e-07 ,  5.0970   5.1596   6.0007   5.1596   5.0970 
7.56e-09 2.13e-09 2.31e-10 2.13e-09 7.56e-09 ,  5.0234   5.0397   5.9999   5.0397   5.0234 
2.35e-10 6.61e-11 3.60e-12 6.61e-11 2.35e-10 ,  5.0058   5.0099   5.9996   5.0099   5.0058 
7.34e-12 2.06e-12 5.66e-14 2.06e-12 7.34e-12 ,  5.0014   5.0025   5.9920   5.0023   5.0015 
2.30e-13 6.44e-14 2.66e-15 6.49e-14 2.29e-13 ,  4.9984   4.9992   4.4094   4.9884   5.0002 
```

**Comment by majosm** [comment]
And with mirgecom:

N == 1:
-------
```
Approximation error:
h         | Error                  | Running EOC       
----------+------------------------+--------------------
0.25      | 0.001812507428979573   |                   
0.125     | 0.0008685919101401685  | 1.0612364873116644
0.0625    | 0.00041330570074016987 | 1.0714692529401424
0.03125   | 0.00020081632530655956 | 1.0413327054506025
0.015625  | 9.890917354519049e-05  | 1.0217003193690444
0.0078125 | 4.907651222395109e-05  | 1.0110716100588695

Overall EOC: 1.0422540404109015
```

N == 2:
-------
```
Approximation error:
h         | Error                  | Running EOC       
----------+------------------------+--------------------
0.25      | 0.0010901584998355663  |                   
0.125     | 0.0003454667316084437  | 1.657919214810971 
0.0625    | 7.062730577715678e-05  | 2.290248817883641 
0.03125   | 8.686358018221868e-06  | 3.0234027415394444
0.015625  | 1.0337338637657822e-06 | 3.070886606757139 
0.0078125 | 1.2615285240716807e-07 | 3.0346200774199303

Overall EOC: 2.6732115580610167
```

N == 3:
-------
```
Approximation error:
h         | Error                  | Running EOC       
----------+------------------------+--------------------
0.25      | 0.00013252693807455963 |                   
0.125     | 1.0827352951291291e-05 | 3.613533154657686 
0.0625    | 9.803196035484445e-07  | 3.4652845957614042
0.03125   | 1.0206566109315762e-07 | 3.263754604551616 
0.015625  | 1.1903817949885491e-08 | 3.1000012953398737
0.0078125 | 1.4457173084027416e-09 | 3.0415669836355126

Overall EOC: 3.290616550321163
```

N == 4:
-------
```
Approximation error:
h         | Error                  | Running EOC       
----------+------------------------+--------------------
0.25      | 2.033692100596094e-05  |                   
0.125     | 5.766507584391846e-07  | 5.140259630053476 
0.0625    | 1.327694340056898e-08  | 5.440702877762206 
0.03125   | 3.539708047232792e-10  | 5.2291488667540955
0.015625  | 1.0200323328308854e-11 | 5.1169435843232876
0.0078125 | 3.066769427007062e-13  | 5.055751370398136 

Overall EOC: 5.214387614277961
```

Seems like I might be getting different stability behavior though. I'll have to look more closely tomorrow.

**Comment by majosm** [comment]
Hmm. After taking another look at this, I'm having some doubts... In the above time-integrating tests, it turns out I was using a non-constant timestep (it varied with spatial resolution, Δt = O(Δx^2)). That could be introducing extra factors of h into the error, right?

When I fix the timestep, the convergence rate returns to the previous non-matching behavior (for both codes). Seems like something is still amiss here...?

**Comment by inducer** [comment]
> That could be introducing extra factors of h into the error, right?

If you mean that we would gain accuracy from it, then I sort of don't believe that. If you have multiple contributors to the error (here, spatial and temporal), then you typically only see the dominant (lowest) power of h. Since dt=dx^2, and given that you probably are using RK4, I would expect the temporal order of accuracy (with respect to refinement of dx) to be 8, so it should be asymptotically vanish compared to the spatial error.

> When I fix the timestep, the convergence rate returns to the previous non-matching behavior (for both codes). Seems like something is still amiss here...?

As I said, I kind of expect spatial error to dominate. What you're doing is effectively temporal refinement, and I find it strange that that would have a measurable effect on the error.

**Comment by majosm** [comment]
> If you mean that we would gain accuracy from it, then I sort of don't believe that. If you have multiple contributors to the error (here, spatial and temporal), then you typically only see the dominant (lowest) power of h. Since dt=dx^2, and given that you probably are using RK4, I would expect the temporal order of accuracy (with respect to refinement of dx) to be 8, so it should be asymptotically vanish compared to the spatial error.

That makes sense.

> As I said, I kind of expect spatial error to dominate. What you're doing is effectively temporal refinement, and I find it strange that that would have a measurable effect on the error.

Yeah, I don't get it either. I'll keep looking.

**Comment by majosm** [comment]
This is interesting. If I integrate longer in time, the spatial order seems to improve. Here are results for N == 2 and dt == 1e-7, varying the number of steps:

10 steps:
--------
```
4.18e-07
2.00e-07,   1.0628
9.86e-08,   1.0203
4.90e-08,   1.0085
2.42e-08,   1.0147
1.17e-08,   1.0537
```

100 steps:
----------
```
4.17e-06
2.00e-06,   1.0647
9.79e-07,   1.0279
4.76e-07,   1.0386
2.17e-07,   1.1325
7.77e-08,   1.4838
```

1000 steps:
-----------
```
4.16e-05
1.96e-05,   1.0837
9.13e-06,   1.1023
3.66e-06,   1.3201
9.04e-07,   2.0164
1.23e-07,   2.8755
```

10k steps:
----------
```
3.98e-04
1.65e-04,   1.2660
5.00e-05,   1.7273
7.87e-06,   2.6656
9.85e-07,   2.9987
1.23e-07,   3.0004
```

Any idea how to make sense of this?

**Comment by inducer** [comment]
> Any idea how to make sense of this?

Actually, yeah, at least sort of. "Close" to the initial condition (i.e. for short times), the spatial discretization does not play any role in the solution (particularly considering the tiny time steps we're forced to take). You can see the errors increase for longer times, and that's the spatial error we're wanting to measure, and it only slowly becomes dominant.

The only negative aspect I can see in this is that we'll have to take tons of time steps in a unit test of this, which could be costly.

**Comment by jbfreund** [comment]
I don't have time just now look at this in detail, and sorry if you've already covered this or maybe it doesn't apply, but don't forget there is a projection error in putting the initial condition onto the basis functions.  I think that this can maybe dominate for some time.  The solution is more accurate going forward than it was in the initialization.  The effects of this will potentially diminish in time for a heat equation.  I think this is maybe mentioned in Hestahaven and Burton.  I'll try an look at it more later.  (Similarly, being off by a delta t would also diminish in time.)

**Comment by majosm** [comment]
> Actually, yeah, at least sort of. "Close" to the initial condition (i.e. for short times), the spatial discretization does not play any role in the solution (particularly considering the tiny time steps we're forced to take). You can see the errors increase for longer times, and that's the spatial error we're wanting to measure, and it only slowly becomes dominant.

I don't know if I'm 100% convinced by this yet, but I can't come up with a better explanation so I'm going to roll with it.

> I don't have time just now look at this in detail, and sorry if you've already covered this or maybe it doesn't apply, but don't forget there is a projection error in putting the initial condition onto the basis functions.

I'm tempted to say that in this particular case at least it shouldn't matter, since the solution at time t is the same in space as the initial solution: u0(x) = cos(x), u(x,t) = exp(-t)*cos(x). I think the projection errors for the computed solution and the expected solution would be the same, and thus cancel out?

> (Similarly, being off by a delta t would also diminish in time.)

As a sanity check I tried offsetting the time by Δt in both directions, and both of them stop converging at some point while refining. So I think we're in good shape there.

**Comment by majosm** [comment]
I found something by accident earlier that seems relevant:

https://www.dam.brown.edu/scicomp/scg-media/report_files/BrownSC-2002-13.pdf

On page 4:

Screen Shot 2020-10-21 at 4 38 28 PM

**Comment by majosm** [comment]
Anybody know how to jumpstart the CI here? @matthiasdiener, @inducer? For some reason it's been stuck at `Expected — Waiting for status to be reported` ever since I created this PR...

**Comment by matthiasdiener** [comment]
> Anybody know how to jumpstart the CI here? @matthiasdiener, @inducer? For some reason it's been stuck at `Expected — Waiting for status to be reported` ever since I created this PR...

I guess it's because you are trying to merge from a fork, but as far as I can see the relevant settings should allow that.

**Pull request closed without merging**
