### PR TITLE
Clean up healthchecking in #381

### PR DESCRIPTION
**Pull request by majosm**
(Only applied to autoignition-mpi for the moment.)

### CODE REVIEW

**Review by MTCam — COMMENTED** [review]
I love this in terms of what it does to the code, but are you concerned with doing two collectives when one reduce could have done the trick?  Or is it that you want the actual exception with its message on all the ranks? Would it be useful to try to dump the message for all ranks, so that we can get them all? There may be disparate exceptions among ranks, if we care.

**Comment by inducer** [comment]
I think this is a good direction, too... quite possibly, we can have a bunch of rank-local health checks and then keep the communication logic entirely separate. (maybe even in `advance_state`?

**Comment by majosm** [comment]
> I love this in terms of what it does to the code, but are you concerned with doing two collectives when one reduce could have done the trick? Or is it that you want the actual exception with its message on all the ranks? Would it be useful to try to dump the message for all ranks, so that we can get them all? There may be disparate exceptions among ranks, if we care.

Synchronizing just seems like the least surprising behavior IMO. Different ranks raising different exceptions could get nasty since they may not be handled the same way. It's probably best to choose one consistently.

The extra broadcast is only incurred if there actually is an exception, so I don't think it should present a performance issue.

**Comment by MTCam** [comment]
> > I love this in terms of what it does to the code, but are you concerned with doing two collectives when one reduce could have done the trick? Or is it that you want the actual exception with its message on all the ranks? Would it be useful to try to dump the message for all ranks, so that we can get them all? There may be disparate exceptions among ranks, if we care.
> 
> Synchronizing just seems like the least surprising behavior IMO. Different ranks raising different exceptions could get nasty since they may not be handled the same way. It's probably best to choose one consistently.
> 

I agree completely about synchronizing, but I am still not convinced the exceptions themselves should be exchanged or synchronized. I think the specificity of the exception is too high.

I think we should synchronize that a fatal error occurred, but let each rank log its own error, and then toss the same exception on all ranks.  Even if it is just ("Some rank had a fatal sim error").  If we let each rank report its errors then we get more information about what went wrong, and it eliminates the need to broadcast or exchange the exceptions as a whole, reducing the complexity of this error handling business.

**Comment by majosm** [comment]
> I agree completely about synchronizing, but I am still not convinced the exceptions themselves should be exchanged or synchronized. I think the specificity of the exception is too high.
> 
> I think we should synchronize that a fatal error occurred, but let each rank log its own error, and then toss the same exception on all ranks. Even if it is just ("Some rank had a fatal sim error"). If we let each rank report its errors then we get more information about what went wrong, and it eliminates the need to broadcast or exchange the exceptions as a whole, reducing the complexity of this error handling business.

I guess I'm ok with this. Generally I think exception specificity is a good thing, since it allows the caller to pick and choose what errors to handle and how. But since these errors aren't likely to be handled except by aborting, it probably doesn't matter that much.

**Pull request closed without merging**
