### PR TITLE
make sure to install mirgecom for doc builds

### PR DESCRIPTION
**Pull request by matthiasdiener**

### CODE REVIEW

**Review by MTCam — APPROVED** [review]
👍

**Comment by majosm** [comment]
This worked for me:

```diff
diff --git a/doc/conf.py b/doc/conf.py
index fd27fad..675ede5 100644
--- a/doc/conf.py
+++ b/doc/conf.py
@@ -10,9 +10,9 @@
 # add these directories to sys.path here. If the directory is relative to the
 # documentation root, use os.path.abspath to make it absolute, like shown here.
 #
-# import os
-# import sys
-# sys.path.insert(0, os.path.abspath('.'))
+import os
+import sys
+sys.path.insert(0, os.path.abspath('..'))
```

**Review by inducer — APPROVED** [review]

**Comment by matthiasdiener** [comment]
Well, this is awkward.

```
Processing dependencies for mirgecom==2020.1
Searching for grudge>=2015.1
Reading https://pypi.org/simple/grudge/
No local packages or working download links found for grudge>=2015.1
error: Could not find suitable distribution for Requirement.parse('grudge>=2015.1')
```

**Comment by matthiasdiener** [comment]
Seems to render documentation correctly now.

**Review by inducer — APPROVED** [review]
Awesome. Thanks for fixing this!

**Pull request merged**
