### PR TITLE
debug memory leak in wave

### PR DESCRIPTION
**Pull request by matthiasdiener**
⚠️  Not meant for merging ⚠️

cc https://github.com/illinois-ceesd/mirgecom/issues/839

### CODE REVIEW

**Comment by matthiasdiener** [comment]
Impact of different workarounds on memory consumption of wave 

| Workaround | Mempool total | Overhead/step | Stable after |
| -------- | -------- | -------- | ----------- |
| None (baseline)    | 14.6 MByte     | --- | Step 1,500 |
| `gc.collect()` every 1 step     | 2.0 MByte     | 0.02 s  | Step 1 |
| `gc.collect()` every 10 steps (current production)  |  4.3 MByte    | 2 ms | Step 10 |
| `gc.set_threshold(1,1,1)` | 6.2 MByte | 0.02 s      | Step 32 |
| **`gc.collect(1)` every 1 step**     | 2.1 MByte     | 0.07 ms  | Step 3 |
| `gc.collect(1)` every 10 steps     | 9.2 MByte     | 0.006 ms  | Step 15,000 |
| `gc.collect(0)` every 1 step     | 10.5 MByte     | 0.07 ms  | Step 800 |
| `gc.collect(0)` every 10 steps     | 14.0 MByte     | 0.006 ms  | Step 7,500 |
| `gc.collect(2)` every 1 step     | 2.0 MByte     | 0.02 s  | Step 1 |
| `gc.collect(2)` every 10 steps     | 4.3 MByte     | 0.002 s  | Step 10 |
| `mempool.free_held()` every 1 step     | 2 - 12 MByte     | 0.01 ms  | Step 1 |

**Comment by matthiasdiener** [comment]
Every time step, approx. 650 objects are garbage collected with the code in this PR. A typedump of those objects is in https://gist.github.com/matthiasdiener/33956f42bbd60321c75ad2ed62ea2fc6 .  A few data structures contain references to PooledSVM allocations. Are these the objects we should focus on?

**Comment by inducer** [comment]
Possibly? They look like somewhat plausible suspects for keeping an array alive.

**Comment by matthiasdiener** [comment]
Here is a reference graph with the objects that are garbage collected on a timestep (made with https://github.com/inducer/pytools/pull/177).



code

**Comment by inducer** [comment]
Do the arrows in the graph point from referred to referent? (i.e. the opposite of the 'refers-to') graph?

**Comment by matthiasdiener** [comment]
> Do the arrows in the graph point from referred to referent?

Yes, this is true. I'll switch https://github.com/inducer/pytools/pull/177 to point the edges in the other direction.

**Pull request closed without merging**
