### PR TITLE
[DO NOT MERGE] Sanity check tests by switching to L2 norm

### PR DESCRIPTION
**Pull request by majosm**
L2 norm avoids https://github.com/inducer/pyopencl/issues/583.

**Questions for the review**:
- [ ] Is the scope and purpose of the PR clear?
  - [ ] The PR should have a description.
  - [ ] The PR should have a guide if needed (e.g., an ordering).
- [ ] Is every top-level method and class documented? Are things that should be documented actually so?
- [ ] Is the interface understandable? (I.e. can someone figure out what stuff does?) Is it well-defined?
- [ ] Does the implementation do what the docstring claims?
- [ ] Is everything that is implemented covered by tests?
- [ ] Do you see any immediate risks or performance disadvantages with the design? Example: what do interface normals attach to?

### CODE REVIEW

**Comment by majosm** [comment]
@MTCam It looks like a few of the tests are producing NaNs (see CI). They aren't detected in main because pyopencl's `min`/`max` (used by `op.norm(..., np.inf)`) aren't handling NaNs correctly at the moment. We should look into these.

**Comment by inducer** [comment]
Not sure I love this idea. I agree that we should catch NaNs, but I feel like we should fix the underlying issue in PyOpenCL instead of switching the norm to $L^2$.  $L^2$ is a weaker norm, meaning it can hide dimension-0 non-convergence up to third order (in 3D) and dimension-1 non-convergence up to second... so there's a lot of potential for non-convergence to go undetected.

**Comment by majosm** [comment]
> Not sure I love this idea. I agree that we should catch NaNs, but I feel like we should fix the underlying issue in PyOpenCL instead of switching the norm to 
> L
> 2
> . 
> L
> 2
>  is a weaker norm, meaning it can hide dimension-0 non-convergence up to third order (in 3D) and dimension-1 non-convergence up to second... so there's a lot of potential for non-convergence to go undetected. Meanwhile, 
> L
> ∞
>  is sensitive to all these things.

Yeah this is a "do not merge" PR (sorry, forgot to mention that explicitly). Just wanted to run CI and see what happens.

**Comment by MTCam** [comment]
> @MTCam It looks like a few of the tests are producing NaNs (see CI). They aren't detected in main because pyopencl's `min`/`max` (used by `op.norm(..., np.inf)`) aren't handling NaNs correctly at the moment. We should look into these.

Thanks! Scary!   Fixed by #713

**Pull request closed without merging**
