### PR TITLE
Trick vortex test case to hand out EOC data

### PR DESCRIPTION
**Pull request by MTCam**
PR for discussion of EOC data from Euler module.  Here's the results of a test of the 2D isentropic vortex case wherein the Euler RHS is checked against the expected (0) for p-order elements:

P = 1
```
Error for (dim,order) = (2,1):
h                   | Error              | Running EOC        
--------------------+--------------------+---------------------
0.6666666666666666  | 1.7441922831117675 |                    
0.3225806451612903  | 1.2752916875582745 | 0.43132757391751286
0.15873015873015872 | 0.7730956445395745 | 0.7058156701834725 
0.0392156862745098   | 0.1999643584725899  | 0.9835017611718138 
0.019569471624266144 | 0.10002099667222199 | 0.9966234897505581 

Overall EOC: 0.8310439764884241
```

P = 2
```
Error for (dim,order) = (2,2):
h                   | Error               | Running EOC       
--------------------+---------------------+--------------------
0.6666666666666666  | 1.5100385589115102  |                   
0.3225806451612903  | 0.6358166704048114  | 1.1915361711120815
0.15873015873015872 | 0.18214371452252343 | 1.762840894708582 
0.0392156862745098   | 0.011578972118560385 | 1.993129088795829 
0.019569471624266144 | 0.002890081385315724 | 1.996682451335228 

Overall EOC: 1.8102480740269564
```

P = 3
```
Error for (dim,order) = (2,3):
h                   | Error                | Running EOC       
--------------------+----------------------+--------------------
0.6666666666666666  | 1.2701267782526717   |                   
0.3225806451612903  | 0.20144842140730326  | 2.5364991945997173
0.15873015873015872 | 0.029276332895191895 | 2.719820456639534 
0.0392156862745098   | 0.0004708729157645916 | 2.9934626226993455
0.019569471624266144 | 5.862347020965949e-05 | 2.997316916791445 

Overall EOC: 2.84291826358655
```

These tests pass due to the line:
```
    assert (
        eoc_rec.order_estimate() >= order - 0.5
        or eoc_rec.max_error() < 1e-11
    )
```

### CODE REVIEW

**Comment by inducer** [comment]
Some observations:

- It's good that the EOC appears to increase with order.
- I assume the errors are relative. (If not, they should be.) If that's so, then errors >= 0.2 are very likely in the pre-asymptotic regime and not relevant/not amenable to being modeled by EOC.
- None of the runs seem to be truly in the asymptotic regime yet. IMO, it would be worthwhile to refine further to see more of the asymptotic behavior.
- My view is that P=3 should exhibit an EOC of 4. (P+1) A first step might be to plot the error (at the fine end) to see what's up. Some of this may be aliasing-driven.

cc @lukeolson as the numerics czar

**Comment by MTCam** [comment]
> Some observations:
> 
> * It's good that the EOC appears to increase with order.  
(!) Heh, a consolation prize.

> * I assume the errors are relative. (If not, they should be.) If that's so, then errors >= 0.2 are very likely in the pre-asymptotic regime and not relevant/not amenable to being modeled by EOC.
This particular experiment is designed to have  RHS 0 everywhere; a static vortex, so the RHS errors are absolute.  Is this a problem?
   
> * None of the runs seem to be truly in the asymptotic regime yet. IMO, it would be worthwhile to refine further to see more of the asymptotic behavior.
I have updated the tabular output of the EOC object with two more levels.  This appears to be enough - what do you think?

> * My view is that P=3 should exhibit an EOC of 4. (P+1) A first step might be to plot the error (at the fine end) to see what's up. Some of this may be aliasing-driven.
> 
Here are what the errors in mass RHS look like centered on the vortex itself for the 512x512 case.
Screen Shot 2020-09-17 at 12 52 59 PM


> cc @lukeolson as the numerics czar

**Comment by inducer** [comment]
> This particular experiment is designed to have RHS 0 everywhere; a static vortex, so the RHS errors are absolute. Is this a problem?

I'm not sure what the RHS has to do with it. I was expecting `norm(true-actual)/norm(true)`. That's more informative than `norm(true-actual)`.

>  I have updated the tabular output of the EOC object with two more levels. This appears to be enough - what do you think?

Yes, that's pretty clear. Thanks. It's pretty obvious that it gives us P instead of P+1. Could you check the JSH/TW book for what convergence orders they report?

> Here are what the errors in mass RHS look like centered on the vortex itself for the 512x512 case.

There are some artifacts in that plot. Are those real? If so, I'd consider them a problem. Could you share the VTU somehere? (maybe via a link to Box?)

**Comment by MTCam** [comment]
> > This particular experiment is designed to have RHS 0 everywhere; a static vortex, so the RHS errors are absolute. Is this a problem?
> 
> I'm not sure what the RHS has to do with it. I was expecting `norm(true-actual)/norm(true)`. That's more informative than `norm(true-actual)`.

My point is that in the description of this PR (including the tables), we are looking at the RHS and the errors in the RHS, and the true RHS is 0.   

If I actually integrate in time a non-trivial case, and check the relative error in the solution after 10 steps, I have the following (similar) table:

Advecting 2D Vortex
```
Error for (dim,order) = (2,3):
h          | Error                  | Running EOC       
-----------+------------------------+--------------------
0.0625     | 2.27021517446834e-07   |                   
0.03125    | 3.240110374356007e-08  | 2.808714180376123 
0.015625   | 6.788568210156446e-09  | 2.254863729242696 
0.0078125  | 8.330178221688342e-10  | 3.0266880579310302
0.00390625 | 1.0548276527452338e-10 | 2.9813400642919685

Overall EOC: 2.742476385085735
```

> 
> > I have updated the tabular output of the EOC object with two more levels. This appears to be enough - what do you think?
> 
> Yes, that's pretty clear. Thanks. It's pretty obvious that it gives us P instead of P+1. Could you check the JSH/TW book for what convergence orders they report?
> 

They report optimum should be O(h^(N + 1/2)) just after table 6.2. :(

> > Here are what the errors in mass RHS look like centered on the vortex itself for the 512x512 case.
> 
> There are some artifacts in that plot. Are those real? If so, I'd consider them a problem. Could you share the VTU somehere? (maybe via a link to Box?)

Sorry about those awful viz artifacts.  Let's see if this one is any better.  Do you have an LC account?  I can give you the whole dataset there.

Screen Shot 2020-09-17 at 2 06 17 PM

**Comment by inducer** [comment]
> They report optimum should be O(h^(N + 1/2)) just after table 6.2. :(

Do their empirical results match that?

>  viz artifacts. Let's see if this one is any better. 

No obvious artifacts, but that looks substantially underresolved.

>  Do you have an LC account?

No. Still winding its way through the bureaucracy.

**Comment by MTCam** [comment]
> > They report optimum should be O(h^(N + 1/2)) just after table 6.2. :(
> 
> Do their empirical results match that?

Yes. 

> 
> > viz artifacts. Let's see if this one is any better.
> 
> No obvious artifacts, but that looks substantially underresolved.

Heh yeah, it's way coarse.  Just wanted the grid lines in that snap.   I will put the VTU files on porter:/tmp. They are `vortex_error_{order}_{npoints_1d}`.  We can share files more easily when those accounts get added.



> 
> > Do you have an LC account?
> 
> No. Still winding its way through the bureaucracy.

**Comment by inducer** [comment]
Running
```
pycl test_grudge.py  'test_convergence_advec(acf, "rect2", list(range(3, 12)), "strong", "upwind", 3)'   
```
on https://github.com/inducer/grudge/commit/48e11e10626b01e001c2bfd245d4c74a996856d4 with this diff
```diff
diff --git a/test/test_grudge.py b/test/test_grudge.py
index 9fd6ca3..979b591 100644
--- a/test/test_grudge.py
+++ b/test/test_grudge.py
@@ -41,6 +41,10 @@ import logging
 logger = logging.getLogger(__name__)
 
 
+def acf():
+    return PyOpenCLArrayContext(cl.CommandQueue(cl.create_some_context()))
+
+
 # {{{ inverse metric
 
 @pytest.mark.parametrize("dim", [2, 3])
@@ -666,6 +670,7 @@ def test_convergence_advec(actx_factory, mesh_name, mesh_pars, op_type, flux_typ
 
     from pytools.convergence import EOCRecorder
     eoc_rec = EOCRecorder()
+    logging.basicConfig(level="INFO")
 
     for mesh_par in mesh_pars:
         if mesh_name == "segment":
```
gives me
```
INFO:__main__:
h                   | L2 Error               | Running EOC       
--------------------+------------------------+--------------------
0.35355339059327423 | 0.050523616021976366   |                   
0.2357022603955163  | 0.008967569491133653   | 4.263810021585468 
0.17677669529663742 | 0.003103316786407228   | 3.688596929065288 
0.14142135623731014 | 0.001294381525292201   | 3.918726178946788 
0.11785113019775863 | 0.0005705426732651939  | 4.493162089786185 
0.10101525445522173 | 0.00025229192782673653 | 5.293529074232992 
0.08838834764831907 | 0.0001183496145905417  | 5.668657882469154 
0.07856742013183932 | 7.25214422770306e-05   | 4.158160833806393 
0.07071067811865538 | 5.7831115955297e-05    | 2.1483883512944844

Overall EOC: 4.308396343171053
```

**Pull request closed without merging**
