### PR TITLE
Refactor EOS to accept conserved fields 

### PR DESCRIPTION
**Pull request by inducer**
cc @MTCam

### CODE REVIEW

**Comment by MTCam** [comment]
@inducer Merging this will fix the remaining CI errors on AKEH. Cheerio!

**Comment by inducer** [comment]
@MTCam This still shows "Draft" status. Was that intentional? Or is it good to go?

**Comment by MTCam** [comment]
Unintentional.

**Comment by inducer** [comment]
(Also: be careful not to "squash and merge". I think you want to create a merge commit.)

**Pull request merged**
