### PR TITLE
Switch grudge back to main

### PR DESCRIPTION
**Pull request by majosm**
Doesn't need to be on a branch anymore now that inducer/grudge#280 is merged.

**Questions for the review**:
- [ ] Is the scope and purpose of the PR clear?
  - [ ] The PR should have a description.
  - [ ] The PR should have a guide if needed (e.g., an ordering).
- [ ] Is every top-level method and class documented? Are things that should be documented actually so?
- [ ] Is the interface understandable? (I.e. can someone figure out what stuff does?) Is it well-defined?
- [ ] Does the implementation do what the docstring claims?
- [ ] Is everything that is implemented covered by tests?
- [ ] Do you see any immediate risks or performance disadvantages with the design? Example: what do interface normals attach to?

### CODE REVIEW

**Comment by matthiasdiener** [comment]
should this point to Kauhik's fork?

**Comment by majosm** [comment]
> should this point to Kaushik's fork?

Dunno, it's the same as Andreas' right now (or at least it was before the multi-volume stuff went in).

@kaushikcfd Are you planning to add any fusion stuff to your grudge in the near future?

**Comment by majosm** [comment]
I think we can go ahead with this as is and switch it over to Kaushik's if/when needed.

**Review by matthiasdiener — APPROVED** [review]

**Comment by kaushikcfd** [comment]
> Are you planning to add any fusion stuff to your grudge in the near future?

No. I think `grudge` is feature complete with https://github.com/inducer/grudge/pull/260.

**Pull request merged**
