### PR TITLE
mpi4py workaround

### PR DESCRIPTION
**Pull request by matthiasdiener**
- https://github.com/mpi4py/mpi4py/issues/157
- https://github.com/illinois-ceesd/emirge/pull/143
- https://github.com/illinois-ceesd/mirgecom/pull/584

### CODE REVIEW

**Comment by matthiasdiener** [comment]
@inducer: What is your opinion on this PR vs #584? This PR seems to be a bit simpler, but does not explicitly address Cython (which I'm not sure how important it is).

**Comment by inducer** [comment]
I like the simplicity of this, but it doesn't seem to address the Cython issue for Emirge and production? Though TBH I'm not sure I understand why #584 would. Let me rerun the CI for it, to maybe level the playing field/understand better.

**Comment by matthiasdiener** [comment]
> I like the simplicity of this, but it doesn't seem to address the Cython issue for Emirge and production? Though TBH I'm not sure I understand why #584 would. Let me rerun the CI for it, to maybe level the playing field/understand better.

I _think_ Emirge/production need https://github.com/illinois-ceesd/emirge/pull/143 to pass and would be hopefully fine when that merges. CI has been super-flaky lately for some reason...

**Comment by inducer** [comment]
If that works, then I think that's perfect. I forgot to approve https://github.com/illinois-ceesd/emirge/pull/143, did that just now. Depending on CI flakiness, it might merge soon, and we can try this out.

**Review by inducer — APPROVED** [review]
Looks like it works. Thanks for for figuring this out!

**Pull request merged**
