### PR TITLE
mtc/euler-mpi

### PR DESCRIPTION
**Pull request by MTCam**
Trying to start a draft PR for the MPI-enabled Euler solver.

### CODE REVIEW

**Comment by inducer** [comment]
Shouldn't this be on top of the `array-context` branch? See [this commit](https://gitlab.tiker.net/inducer/grudge/-/commit/f54331008713920bdd7a020f528f4a8894b748de) for how MPI can work. There should also be an MPI test that runs as part of CI. See grudge CI for how to do that.

**Comment by MTCam** [comment]
I didn't realize the two were dependent. I created two separate pull requests; one for the MPI and one for the array-context port.  They were indeed together before the PRs and I ripped them apart.  Sigh.

**Comment by MTCam** [comment]
I think the thing to do here is ignore this one, and just look at the array-context PR #13 .  I'll add MPI into the description. 

I was unable to find the MPI jobs in the grudge CI.  I looked in: <grudge>/workflows/ci.yml, where I do find it installs OpenMPI.  The [ci-support script that it uses](https://gitlab.tiker.net/inducer/ci-support/-/blob/master/build-and-test-py-project-within-miniconda.sh) didn't seem to have any MPI inside.  Am I looking in the wrong spot?

**Comment by MTCam** [comment]
Couldn't figure out how to delete.

**Comment by matthiasdiener** [comment]
> Couldn't figure out how to delete.

You generally can't delete PRs or issues, just close them.

**Pull request closed without merging**
