### PR TITLE
profiling: don't carry kwargs around

### LINKED ISSUE #177: Memory-allocation related crash with profiling on GPU
When running (e.g.) vortex-mpi with profiling enabled, and a somewhat larger input size (`nel_1d = 200`), mirgecom crashes with the following error: 

```
building face restriction: done
Traceback (most recent call last):
  File "/g/g91/diener3/Work/emirge/miniforge3/envs/dgfem/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/g/g91/diener3/Work/emirge/miniforge3/envs/dgfem/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/g/g91/diener3/Work/emirge/miniforge3/envs/dgfem/lib/python3.8/site-packages/mpi4py/__main__.py", line 7, in <module>
    main()
  File "/g/g91/diener3/Work/emirge/miniforge3/envs/dgfem/lib/python3.8/site-packages/mpi4py/run.py", line 196, in main
    run_command_line(args)
  File "/g/g91/diener3/Work/emirge/miniforge3/envs/dgfem/lib/python3.8/site-packages/mpi4py/run.py", line 47, in run_command_line
    run_path(sys.argv[0], run_name='__main__')
  File "/g/g91/diener3/Work/emirge/miniforge3/envs/dgfem/lib/python3.8/runpy.py", line 265, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/g/g91/diener3/Work/emirge/miniforge3/envs/dgfem/lib/python3.8/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/g/g91/diener3/Work/emirge/miniforge3/envs/dgfem/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "vortex-mpi.py", line 174, in <module>
    main()
  File "/usr/WS1/diener3/Work/emirge/mirgecom/mirgecom/mpi.py", line 81, in wrapped_func
    func(*args, **kwargs)
  File "vortex-mpi.py", line 147, in main
    advance_state(rhs=my_rhs, timestepper=timestepper,
  File "/usr/WS1/diener3/Work/emirge/mirgecom/mirgecom/steppers.py", line 79, in advance_state
    state = timestepper(state=state, t=t, dt=dt, rhs=rhs)
  File "/usr/WS1/diener3/Work/emirge/mirgecom/mirgecom/integrators.py", line 41, in rk4_step
    k2 = rhs(t+dt/2, state + dt/2*k1)
  File "vortex-mpi.py", line 133, in my_rhs
    return inviscid_operator(discr, q=state, t=t,
  File "/usr/WS1/diener3/Work/emirge/mirgecom/mirgecom/euler.py", line 264, in inviscid_operator
    vol_flux = inviscid_flux(discr, eos, q)
  File "/usr/WS1/diener3/Work/emirge/mirgecom/mirgecom/euler.py", line 181, in inviscid_flux
    momentum=np.outer(mom, mom)/cv.mass + np.eye(dim)*p)
  File "/usr/WS1/diener3/Work/emirge/meshmode/meshmode/dof_array.py", line 177, in __add__
    def __add__(self, arg): return self._bop(op.add, self, arg)  # noqa: E704
  File "/usr/WS1/diener3/Work/emirge/meshmode/meshmode/dof_array.py", line 167, in _bop
    return self._like_me([
  File "/usr/WS1/diener3/Work/emirge/meshmode/meshmode/dof_array.py", line 168, in <listcomp>
    f(op1_i, op2_i)
  File "/usr/WS1/diener3/Work/emirge/pyopencl/pyopencl/array.py", line 1013, in __add__
    result = self._new_like_me(
  File "/usr/WS1/diener3/Work/emirge/pyopencl/pyopencl/array.py", line 966, in _new_like_me
    return self.__class__(queue, self.shape, dtype,
  File "/usr/WS1/diener3/Work/emirge/pyopencl/pyopencl/array.py", line 536, in __init__
    self.base_data = self.allocator(alloc_nbytes)
pyopencl._cl.MemoryError: memory_pool::allocate failed: MEM_OBJECT_ALLOCATION_FAILURE - failed to free memory for allocation
```

This only happens when running on the GPU, not on CPU.

I've tracked this to the handling of the lists of ProfileEvents in mirgecom/profiling.py:

https://github.com/illinois-ceesd/mirgecom/blob/31467cc8cfc6f752392dad99d221a190ce65791f/mirgecom/profiling.py#L229

```python
@dataclass
class ProfileEvent:
    """Class to hold a profile event that has not been seen by the profiler yet."""

    cl_event: cl._cl.Event
    program: lp.kernel.LoopKernel
    kwargs: dict
```

At the time of the above crash, the list is relatively small (18 KByte memory). It seems that these ProfileEvents are somehow allocated on the device?
In the above code, replacing

```python
self.profile_events.append(ProfileEvent(evt, program, kwargs))
```

with 

```python
foo = ProfileResult(1,2,3,4)
self.profile_events.append(foo)
```

(ie, changing ProfileEvent to ProfileResult) seems to work fine.

### PR DESCRIPTION
**Pull request by matthiasdiener**
Fixes #177.
Approx. ~10%~ -2% overhead vs. profiling with `master` branch.

### CODE REVIEW

**Review by inducer — APPROVED** [review]
LGTM, thanks for working on this. As to your comment regarding 10% overhead, what is the baseline? Does this represent an increase in overhead? If so, where's that coming from? I don't see any change that I would spontaneously blame for a cost increase.

**Comment by matthiasdiener** [comment]
> LGTM, thanks for working on this. As to your comment regarding 10% overhead, what is the baseline? Does this represent an increase in overhead? If so, where's that coming from? I don't see any change that I would spontaneously blame for a cost increase.

The baseline is profiling without this PR, ie, 10% additional overhead compared to the normal profiling overhead. I believe this is due to calling `_cache_kernel_stats()` (which transforms `kwargs` into `args_tuple`) on every kernel call. I have not found a way around that (or to cache the args_tuple).

**Comment by matthiasdiener** [comment]
Part of 

> > LGTM, thanks for working on this. As to your comment regarding 10% overhead, what is the baseline? Does this represent an increase in overhead? If so, where's that coming from? I don't see any change that I would spontaneously blame for a cost increase.
> 
> The baseline is profiling without this PR, ie, 10% additional overhead compared to the normal profiling overhead. I believe this is due to calling `_cache_kernel_stats()` (which transforms `kwargs` into `args_tuple`) on every kernel call. I have not found a way around that (or to cache the args_tuple).

As a side question: part of the overhead seems to come from the fact that `hash(program)` seems to be quite slow - about 0.3 ms, two orders of magnitude slower than `hash(program.name)`. Is this expected?

**Comment by inducer** [comment]
> As a side question: part of the overhead appears to come from the fact that `hash(program)` is quite slow - about 0.3 ms, two orders of magnitude slower than `hash(program.name)`. Is this expected?

It's expected that it is slow the first time it happens. (A hash of the whole program needs to be computed, after all. Every expression, every variable definition, the whole thing.) It should however not *stay* slow. But I think we can make it fast the second and following times: https://github.com/inducer/loopy/pull/185

**Comment by matthiasdiener** [comment]
> > As a side question: part of the overhead appears to come from the fact that `hash(program)` is quite slow - about 0.3 ms, two orders of magnitude slower than `hash(program.name)`. Is this expected?
> 
> It's expected that it is slow the first time it happens. (A hash of the whole program needs to be computed, after all. Every expression, every variable definition, the whole thing.) It should however not _stay_ slow. But I think we can make it fast the second and following times: [inducer/loopy#185](https://github.com/inducer/loopy/pull/185)

Nice, thanks! ;-)

**Comment by inducer** [comment]
https://github.com/inducer/loopy/pull/185 is merged. Could you try again and report overhead?

**Comment by matthiasdiener** [comment]
I ran these a few times but still can not believe my lying eyes:

(Lassen/pocl/GPU; Vortex2D/450 elements/100 time steps)

| Wall time in seconds | Loopy without inducer/loopy#185 | Loopy with inducer/loopy#185  |
|----------------------|-----------|-----------|
| No profiling         | 57.0s      | 50.9s      |
| Old profiling (current `master`)       | 85.9s      | 55.7s      |
| New profiling (with #179)      | 95.6s     | 54.4s      |

**Comment by inducer** [comment]
Huh, nice. I'm glad we dug into the overhead a bit more. This looks good to merge then, especially given that it seems to have negative overhead now. :P

**Pull request merged**
