### PR TITLE
Remove doc link to non-existent pyro Thermochemistry class doc

### PR DESCRIPTION
**Pull request by MTCam**
**Questions for the review**:
- [ ] Is the scope and purpose of the PR clear?
  - [ ] The PR should have a description.
  - [ ] The PR should have a guide if needed (e.g., an ordering).
- [ ] Is every top-level method and class documented? Are things that should be documented actually so?
- [ ] Is the interface understandable? (I.e. can someone figure out what stuff does?) Is it well-defined?
- [ ] Does the implementation do what the docstring claims?
- [ ] Is everything that is implemented covered by tests?
- [ ] Do you see any immediate risks or performance disadvantages with the design? Example: what do interface normals attach to?

### CODE REVIEW

**Comment by matthiasdiener** [comment]
Would :class:`pyrometheus.thermochem_example.Thermochemistry` work?

**Comment by inducer** [comment]
> Would :class:`pyrometheus.thermochem_example.Thermochemistry` work?

It should. As of https://github.com/pyrometheus/pyrometheus/issues/65, the relevant code is being included in the doc build.

**Comment by MTCam** [comment]
> > Would :class:`pyrometheus.thermochem_example.Thermochemistry` work?
> 
> It should. As of [pyrometheus/pyrometheus#65](https://github.com/pyrometheus/pyrometheus/issues/65), the relevant code is being included in the doc build.

Agreed, but it didn't fix it.  RTD on pyro appears to be broken.  It is indeed generating the example mechanism, but that mechanism is unloadable/invisible when the docs try to build in RTD.   

@matthiasdiener gave me this log from RTD (https://readthedocs.org/api/v2/build/19198872.txt)... looking at that:

Pyro RTD reports that it is generating the file:
```
[rtd-command-info] start-time: 2023-01-18T00:18:24.565871Z, end-time: 2023-01-18T00:18:25.154374Z, duration: 0, exit-code: 0
python .ci/generate-example-mech.py test/mechs/sandiego.yaml pyrometheus/thermochem_example.py
.ci/generate-example-mech.py:11: DeprecationWarning: cti_to_mech_file should be imported from pyrometheus.codegen.python now. This alias in the root will go away in 2022.
  pyro.cti_to_mech_file(cti_file_name, mech_file_name)
```

That seems OK, but then at doc build time it makes these errors:

```
WARNING: autodoc: failed to import module 'thermochem_example' from module 'pyrometheus'; the following exception was raised:
No module named 'pyrometheus.thermochem_example'

(...)

/home/docs/checkouts/readthedocs.org/user_builds/pyrometheus/conda/latest/lib/python3.8/site-packages/pyrometheus/codegen/python.py:docstring of pyrometheus.codegen.python.gen_thermochem_code:1: WARNING: py:class reference target not found: pyrometheus.thermochem_example.Thermochemistry
```

**Comment by matthiasdiener** [comment]
https://github.com/pyrometheus/pyrometheus/pull/66 should fix this.

**Pull request closed without merging**
