### PR TITLE
Run flake8 in Github CI on target Py version

### PR DESCRIPTION
**Pull request by inducer**

### CODE REVIEW

**Comment by inducer** [comment]
Huh, interesting. It found something!

**Comment by MTCam** [comment]
> Huh, interesting. It found something!

Any ideas on how to fix?  It just says `Invalid syntax`.

**Comment by inducer** [comment]
You can use
```
conda create -n somename python=3.6
```
to make a conda env that has Python 3.6.

This says:
```
  File "<fstring>", line 1
    (step=)
         ^
SyntaxError: invalid syntax
```
for `mirgecom/io.py` and similarly for the `{something=}` f-string in the autoignition example.

The bigger question here is, should we pursue 3.6 compatibility, or should we bump to 3.8, which likes these files just fine?

**Comment by inducer** [comment]
Looks like emirge install is currently broken. @matthiasdiener, could you take a look?

**Comment by inducer** [comment]
@matthiasdiener Thanks for taking a look!

**Review by matthiasdiener — APPROVED** [review]

**Comment by inducer** [comment]
No objections so far, so I say let's just make it official. (We can always change back, with, so far, limited effort.)

**Pull request merged**
