### PR TITLE
add a check for ISL version

### PR DESCRIPTION
**Pull request by matthiasdiener**
Code based on https://github.com/inducer/islpy/issues/28#issuecomment-702408541

---

**Questions for the review**:
- [ ] Is the scope and purpose of the PR clear?
  - [ ] The PR should have a description.
  - [ ] The PR should have a guide if needed (e.g., an ordering).
- [ ] Is every top-level method and class documented? Are things that should be documented actually so?
- [ ] Is the interface understandable? (I.e. can someone figure out what stuff does?) Is it well-defined?
- [ ] Does the implementation do what the docstring claims?
- [ ] Is everything that is implemented covered by tests?
- [ ] Do you see any immediate risks or performance disadvantages with the design? Example: what do interface normals attach to?

### CODE REVIEW

**Comment by inducer** [comment]
It might be worth having this in loopy instead?

**Comment by MTCam** [comment]
> It might be worth having this in loopy instead?

Could someone update kaushikcfd's fork if it does go into loopy?  Would be cool if we could just take that over and make it illinois-ceesd/loopy, then we could keep it updated for ourselves.

**Comment by matthiasdiener** [comment]
> It might be worth having this in loopy instead?

I'm not sure - this code only works since we use the `isl` package from conda-forge, which only provides the `gmp` and `imath32` variants, but not `imath`. I have not found a way to differentiate between `imath` and `imath32` via this method, so in a general installation, we can not be sure if isl is the "very fast" or "very slow" variant...

**Comment by inducer** [comment]
That's a fair point.

**Comment by MTCam** [comment]
Do we want to go ahead and merge this here, then?

**Review by MTCam — APPROVED** [review]

**Pull request merged**
