### PR TITLE
remove vtk from default install

### PR DESCRIPTION
**Pull request by matthiasdiener**
Closes: #658

**Questions for the review**:
- [ ] Is the scope and purpose of the PR clear?
  - [ ] The PR should have a description.
  - [ ] The PR should have a guide if needed (e.g., an ordering).
- [ ] Is every top-level method and class documented? Are things that should be documented actually so?
- [ ] Is the interface understandable? (I.e. can someone figure out what stuff does?) Is it well-defined?
- [ ] Does the implementation do what the docstring claims?
- [ ] Is everything that is implemented covered by tests?
- [ ] Do you see any immediate risks or performance disadvantages with the design? Example: what do interface normals attach to?

### CODE REVIEW

**Review by inducer — APPROVED** [review]
Thx!

**Comment by matthiasdiener** [comment]
I'm not sure what to do about the production merge error @MTCam

**Comment by MTCam** [comment]
Ah sorry, just now seeing this.  I'll fix the production error.

**Comment by matthiasdiener** [comment]
Note that this currently doesn't affect `production`, which pulls vtk back in (through `gmsh`).

**Pull request merged**
