### PR TITLE
Switch element boundary figure to TikZ

### PR DESCRIPTION
**Pull request by inducer**
Works surprisingly well on my machine after
```
pip install sphinxcontrib-tikz
```
Separate PR because it might wedge the CI.

### CODE REVIEW

**Comment by matthiasdiener** [comment]
Do we need latex to build the HTML documentation now?

**Comment by MTCam** [comment]
> Do we need latex to build the HTML documentation now?

I think we always have, CI runs `make latexpdf`

**Comment by MTCam** [comment]
> Do we need latex to build the HTML documentation now?

Haven't we always? There are tex formulas in the RST.  Are those rendered with something else when building html docs?

**Review by MTCam — APPROVED** [review]
Thanks for doing this!  I plan to just merge this.

**Comment by matthiasdiener** [comment]
> > Do we need latex to build the HTML documentation now?
> 
> Haven't we always? There are tex formulas in the RST. Are those rendered with something else when building html docs?

I _think_ the HTML build (which is what I do locally) does not need Latex.

**Comment by MTCam** [comment]
> > > Do we need latex to build the HTML documentation now?
> > 
> > 
> > Haven't we always? There are tex formulas in the RST. Are those rendered with something else when building html docs?
> 
> I _think_ the HTML build (which is what I do locally) does not need Latex.

Is this a show stopper?

**Comment by matthiasdiener** [comment]
> Is this a show stopper?

I don't think so, but I was just curious. Without Latex, the HTML documentation still builds with this PR, but generates the following warning in the output HTML files: 
image

**Comment by MTCam** [comment]
> > Is this a show stopper?
> 
> I don't think so, but I was just curious. Without Latex, the HTML documentation still builds with this PR, but generates the following warning in the output HTML files:
> 
Heh, wow.  That seems substantially less useful than a PNG.

**Comment by MTCam** [comment]
I just delayed this since it is clean and should merge without issue.  I do not have a good sense of whether it will prevent some from building the HTML docs, or whether the latex-dependence is a cause-for-concern.

**Comment by inducer** [comment]
- @MTCam how come you pressed update by merging? The whole PR is now a mess of conflicts... 
- I will not be shepherding this PR. If one of you likes it enough, feel free to take this over.

**Comment by MTCam** [comment]
> * @MTCam how come you pressed update by merging? The whole PR is now a mess of conflicts...
> * I will not be shepherding this PR. If one of you likes it enough, feel free to take this over.

Since I do not understand what you mean, I guess it was unintentional?  I also don't understand how it is a mess now?  The change set did not appear to change.

**Comment by inducer** [comment]
> Edit: Oh I see now. All I can say is sorry, this was unintentional. Just my clumsiness with git.

No worries. Learning how to rebase to manage history might be a worthwhile thing going forward.

**Comment by inducer** [comment]
FTFY.

**Pull request closed without merging**
