### PR TITLE
CI: make lazy examples run distributed

### PR DESCRIPTION
**Pull request by matthiasdiener**
**Questions for the review**:
- [ ] Is the scope and purpose of the PR clear?
  - [ ] The PR should have a description.
  - [ ] The PR should have a guide if needed (e.g., an ordering).
- [ ] Is every top-level method and class documented? Are things that should be documented actually so?
- [ ] Is the interface understandable? (I.e. can someone figure out what stuff does?) Is it well-defined?
- [ ] Does the implementation do what the docstring claims?
- [ ] Is everything that is implemented covered by tests?
- [ ] Do you see any immediate risks or performance disadvantages with the design? Example: what do interface normals attach to?

### CODE REVIEW

**Comment by MTCam** [comment]
Can we add comparisons for these example results for the eager vs. lazy runs?  I think we just need to add the names of the examples we want to test to `test_lazy_accuracy.sh`.

**Comment by matthiasdiener** [comment]
> Can we add comparisons for these example results for the eager vs. lazy runs? I think we just need to add the names of the examples we want to test to `test_lazy_accuracy.sh`.

Which ones should we add? I think adding all of them will make this CI test very slow.

**Comment by MTCam** [comment]
> > Can we add comparisons for these example results for the eager vs. lazy runs? I think we just need to add the names of the examples we want to test to `test_lazy_accuracy.sh`.
> 
> Which ones should we add? I think adding all of them will make this CI test very slow.

I'm not sure - if they run in lazy I think they are already generating all the data.  We just need to run the comparison util.  If the lazy compares run the examples multiple times then we should fix that so that it doesn't do that any more to speed up CI.   If they run both eager and lazy, I think we should check the results (i.e., if it is not costly).

**Review by inducer — APPROVED** [review]
More CI is always better. You guys decide what you'd like cost-wise. :)

**Comment by MTCam** [comment]
I just want to make sure we keep our eye on this ().   When this change propagates up through main - running `mixture-mpi.py` currently hangs. (#645)

**Comment by MTCam** [comment]
Safe to close?   The lazy examples are running distributed now.

**Comment by matthiasdiener** [comment]
Sure, it's fine to close this. Should we start removing the `-lazy` symlinks?

**Pull request closed without merging**
