### PR TITLE
Dangle requirements.txt in Euler branch to pre-array-context

### PR DESCRIPTION
**Pull request by inducer**
@MTCam This will aim your Euler branch at the `pre-array-context` branches of grudge and meshmode.

NB: Needs #24 to actually do anything.

### CODE REVIEW

**Comment by MTCam** [comment]
Should I just pull, port and push to stay with grudge/meshmode proper?

**Comment by inducer** [comment]
> Should I just pull, port and push to stay with grudge/meshmode proper?

pull, port and push what? (Sorry, not sure what you mean.)

**Comment by MTCam** [comment]
I was wondering whether I should go ahead and move to array-context in the Euler branch.

**Comment by inducer** [comment]
Go for it. Then you can close this

**Comment by MTCam** [comment]
I'm having a lot of trouble getting simple stuff to work in the array-context port.  Can you help me with this, @inducer?

```
___________________________________ ERROR collecting test/test_init.py ___________________________________
ImportError while importing test module '/Users/mtcampbe/CEESD/devel/emirge/mirgecom/test/test_init.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
test_init.py:28: in <module>
    import pyopencl as cl
../../../../../miniforge3/envs/dgfem2/lib/python3.8/site-packages/pyopencl/__init__.py:33: in <module>
    import pyopencl.cltypes  # noqa: F401
../../../../../miniforge3/envs/dgfem2/lib/python3.8/site-packages/pyopencl/cltypes.py:24: in <module>
    from pyopencl.tools import get_or_register_dtype
../../../../../miniforge3/envs/dgfem2/lib/python3.8/site-packages/pyopencl/tools.py:39: in <module>
    from pyopencl._cl import bitlog2  # noqa: F401
E   ImportError: dlopen(/Users/mtcampbe/miniforge3/envs/dgfem2/lib/python3.8/site-packages/pyopencl/_cl.cpython-38-darwin.so, 2): Symbol not found: _clCreateCommandQueueWithProperties
E     Referenced from: /Users/mtcampbe/miniforge3/envs/dgfem2/lib/python3.8/site-packages/pyopencl/_cl.cpython-38-darwin.so
E     Expected in: flat namespace
E    in /Users/mtcampbe/miniforge3/envs/dgfem2/lib/python3.8/site-packages/pyopencl/_cl.cpython-38-darwin.so
```

**Comment by inducer** [comment]
Use otool to check what libOpenCL is being linked against from PyOpenCL's C extension dylib.

**Comment by MTCam** [comment]
Thanks, @inducer.  The way I was trying to create PyOpenCLArrayContext was causing this issue.  I accidentically passed in a cl context instead of a queue.  Working out the remaining kinks now.

**Comment by inducer** [comment]
> The way I was trying to create PyOpenCLArrayContext was causing this issue.

Are you sure? The backtrace you show above shows an error on importing pyopencl for not finding a symbol that should be in the OpenCL ICD loader.

**Comment by MTCam** [comment]
Er.. I "fixed" two things.  I was trying to work on this by just installing an up-to-date pyopencl, meshmode, and grudge into my existing environment.  There were just too many weird errors with that so I started from scratch by reinstalling an entire new environment.  That seemed to clear up a bunch of stuff, too.

I'm still struggling a lot to get what seems like a simple thing working again after the changes.  It seems I need to add stuff to the array_context interface like, for example,  `if_positive`.  I add this as so:
```
    def if_positive(self, criterion, then_, else_, out=None):
        import pyopencl.array as cla
        return cla.if_positive(criterion, then_, else_,
                           out, self.queue)
```
to fix this original code:
```
mass = clarray.if_positive((x_rel - self._x0), rhor, rhol)
energy = clarray.if_positive((x_rel - self._x0), energyr, energyl)
```
changed to the following for array_context:
```
mass = actx.if_positive(x_rel, rhor, rhol)
energy = actx.if_positive(x_rel, energyr, energyl)
```
Yielding this error on testing:
```
/Users/mtcampbe/miniforge3/envs/dgfem3/lib/python3.8/site-packages/pyopencl/compyte/dtypes.py:105: KeyError

During handling of the above exception, another exception occurred:

ctx_factory = <pyopencl.tools.pytest_generate_tests_for_pyopencl.<locals>.ContextFactory object at 0x1153f3370>

    def test_shock_init(ctx_factory):
        cl_ctx = ctx_factory()
        queue = cl.CommandQueue(cl_ctx)
        actx = PyOpenCLArrayContext(queue)
    
        nel_1d = 10
        dim = 2
    
        from meshmode.mesh.generation import generate_regular_rect_mesh
    
        mesh = generate_regular_rect_mesh(
            a=[(0.0,), (1.0,)], b=[(-0.5,), (0.5,)], n=(nel_1d,) * dim
        )
    
        order = 3
        print(f"Number of elements: {mesh.nelements}")
    
        discr = EagerDGDiscretization(actx, mesh, order=order)
        nodes = thaw(actx, discr.nodes())
    
        initr = SodShock1D()
>       initsoln = initr(t=0.0, x_vec=nodes)

test_init.py:158: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
../mirgecom/initializers.py:160: in __call__
    mass = actx.if_positive(xrel, rhor, rhol)
../../meshmode/meshmode/array_context.py:259: in if_positive
    return cla.if_positive(criterion, then_, else_,
/Users/mtcampbe/miniforge3/envs/dgfem3/lib/python3.8/site-packages/pyopencl/array.py:2551: in if_positive
    event1 = _if_positive(out, criterion, then_, else_, queue=queue)
/Users/mtcampbe/miniforge3/envs/dgfem3/lib/python3.8/site-packages/pyopencl/array.py:139: in kernel_runner
    knl = kernel_getter(*args, **kwargs)
/Users/mtcampbe/miniforge3/envs/dgfem3/lib/python3.8/site-packages/pyopencl/array.py:2534: in _if_positive
    return elementwise.get_if_positive_kernel(
<decorator-gen-47>:2: in get_if_positive_kernel
    ???
/Users/mtcampbe/miniforge3/envs/dgfem3/lib/python3.8/site-packages/pyopencl/tools.py:101: in first_arg_dependent_memoize
    result = func(cl_object, *args)
/Users/mtcampbe/miniforge3/envs/dgfem3/lib/python3.8/site-packages/pyopencl/elementwise.py:1041: in get_if_positive_kernel
    return get_elwise_kernel(context, [
/Users/mtcampbe/miniforge3/envs/dgfem3/lib/python3.8/site-packages/pyopencl/elementwise.py:174: in get_elwise_kernel
    func, arguments = get_elwise_kernel_and_types(
/Users/mtcampbe/miniforge3/envs/dgfem3/lib/python3.8/site-packages/pyopencl/elementwise.py:155: in get_elwise_kernel_and_types
    loop_prep = get_arg_offset_adjuster_code(parsed_args) + loop_prep
/Users/mtcampbe/miniforge3/envs/dgfem3/lib/python3.8/site-packages/pyopencl/tools.py:403: in get_arg_offset_adjuster_code
    type=dtype_to_ctype(arg_type.dtype),
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <pyopencl.compyte.dtypes.DTypeRegistry object at 0x10c0ef280>, dtype = dtype('O')

    def dtype_to_ctype(self, dtype):
        if dtype is None:
            raise ValueError("dtype may not be None")
    
        dtype = np.dtype(dtype)
    
        try:
            return self.dtype_to_name[dtype]
        except KeyError:
>           raise ValueError("unable to map dtype '%s'" % dtype)
E           ValueError: unable to map dtype 'object'

/Users/mtcampbe/miniforge3/envs/dgfem3/lib/python3.8/site-packages/pyopencl/compyte/dtypes.py:107: ValueError
```

**Comment by inducer** [comment]
You're pretty close! :)
- As you can see from [the docs](https://documen.tician.de/meshmode/array.html#meshmode.array_context.ArrayContext.np) (and guess from the `np` name), functionality offered under there is supposed to work "just like numpy". `if_positive` is an ad-hoc thing I added that to PyOpenCL doesn't match anything in numpy. The correct thing to add (with tests) is the three-argument form of `np.where`. I'm happy to look at a meshmode PR that does so.
- As for `ValueError: unable to map dtype 'object'`: since the arrays passed to `where` (aka `if_positive`) will be `DOFArray`s (i.e. slightly special object arrays), the function needs to vectorize over object arrays. This can be achieved with [`obj_array_vectorize_n_args`](https://documen.tician.de/pytools/obj_array.html#pytools.obj_array.obj_array_vectorize_n_args) or the decorator `obj_array_vectorized_n_args`.

**Comment by MTCam** [comment]
Can you please extend push permissions to me for meshmode?  If so, I can add the PR.   Thanks!

**Comment by MTCam** [comment]
Also, I do not see any existing tests for any of the other .np facilities.  Can you point me to those?  I just want to add the test of `where` to the proper place.

**Comment by inducer** [comment]
> Can you please extend push permissions to me for meshmode? If so, I can add the PR. Thanks!

Just fork the project and create a PR off a branch in that fork.

> Also, I do not see any existing tests for any of the other .np facilities.

*Cough.* You successfully guilted me into [creating some](https://github.com/inducer/meshmode/pull/14). (You can build your test off that branch.)

**Comment by MTCam** [comment]
PR added here (https://github.com/inducer/meshmode/pull/15) - but I am unsure if I have done this right (i.e. the PR).  I added a test below yours.   There is something wrong with it :)  It seems like it is *trying* to work, but there is a shape issue I'm working out right now.

**Comment by inducer** [comment]
This change has been superseded on #7.

**Pull request closed without merging**
