### PR TITLE
Add override options for array context fallbacks

### PR DESCRIPTION
**Pull request by majosm**
Adds options to `initialize_actx` reflecting the disabling of array context fallbacks and the override options that were added to meshmode/grudge. Also tweaked the implementation to try to simplify the logic a bit.

**Questions for the review**:
- [ ] Is the scope and purpose of the PR clear?
  - [ ] The PR should have a description.
  - [ ] The PR should have a guide if needed (e.g., an ordering).
- [ ] Is every top-level method and class documented? Are things that should be documented actually so?
- [ ] Is the interface understandable? (I.e. can someone figure out what stuff does?) Is it well-defined?
- [ ] Does the implementation do what the docstring claims?
- [ ] Is everything that is implemented covered by tests?
- [ ] Do you see any immediate risks or performance disadvantages with the design? Example: what do interface normals attach to?

### CODE REVIEW

**Comment by matthiasdiener** [comment]
LGTM, in general. Does this require the `production` branches of meshmode/grudge, or does it work with `main ` too?

**Comment by majosm** [comment]
> LGTM, in general. Does this require the `production` branches of meshmode/grudge, or does it work with `main ` too?

I think it needs production of meshmode at least, since the fallback stuff is in `FusionContractorArrayContext`. On the grudge side though, it looks like the relevant code is in inducer/main (it references the fusion array context optionally, if it exists). So I guess potentially my changes could go into main of grudge instead of production?

**Comment by matthiasdiener** [comment]
> So I guess potentially my changes could go into main of grudge instead of production?

Yeah, I think that would make sense. My concern was that when merging this PR, mirgecom would then not run anymore with the main branches of grudge/meshmode.

**Comment by majosm** [comment]
> > So I guess potentially my changes could go into main of grudge instead of production?
> 
> Yeah, I think that would make sense. My concern was that when merging this PR, mirgecom would then not run anymore with the main branches of grudge/meshmode.

I think mirgecom main already depends on production of grudge/meshmode for a couple of things (multivolume coupling and ESDG among them), so that ship may have already sailed. 🙂  But I'll still make a PR into grudge main.

**Comment by MTCam** [comment]
> > > So I guess potentially my changes could go into main of grudge instead of production?
> > 
> > 
> > Yeah, I think that would make sense. My concern was that when merging this PR, mirgecom would then not run anymore with the main branches of grudge/meshmode.
> 
> I think mirgecom main already depends on production of grudge/meshmode for a couple of things (multivolume coupling and ESDG among them), so that ship may have already sailed. 🙂 But I'll still make a PR into grudge main.

I understand the concern, but I'm not sure it makes sense for us to delay the merge to mirgecom@main because it will cause mirgecom@main not to work with grudge@main.   Now that the updates are already merged to ceesd/grudge@production and ceesd/meshmode@production, our prediction cases no longer work out of the box with the ceesd install.   That's kind of a headache.

Is there any harm in merging this _and_ making a PR against grudge@main that can be merged on the long timesscale that usually takes?

**Comment by majosm** [comment]
> Is there any harm in merging this _and_ making a PR against grudge@main that can be merged on the long timesscale that usually takes?

I think that would be OK. @matthiasdiener?

**Review by matthiasdiener — APPROVED** [review]

**Comment by MTCam** [comment]
Awesome. Thanks gents!

**Pull request merged**
